import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const workflow = readFileSync(new URL('../.github/workflows/CD.yml', import.meta.url), 'utf8')
const transaction = readFileSync(new URL('../deploy/deploy-content-transaction.sh', import.meta.url), 'utf8')
const installer = readFileSync(new URL('../deploy/install-host-nginx-snippet.sh', import.meta.url), 'utf8')

const functionBody = (source, name, nextName) => source.slice(
  source.indexOf(`${name}() {`),
  source.indexOf(`${nextName}() {`),
)

describe('release delivery contract', () => {
  it('serializes release jobs without cancelling a transaction in flight', () => {
    expect(workflow).toMatch(/concurrency:\s+[\s\S]*group: contests-docs-release[\s\S]*cancel-in-progress: false/)
    expect(transaction).toContain('readonly REDEPLOY_LOCK="${LOCK_DIRECTORY}/redeploy.lock"')
    expect(transaction).toContain("readonly DEPLOY_STATE_ROOT='/var/lib/darebay-deploy'")
    expect(transaction).toContain('ensure_private_lock "$REDEPLOY_LOCK"')
    expect(installer).toContain('lock_file=$lock_directory/nginx-config.lock')
    expect(installer).toContain('ensure_private_lock "$lock_file"')
    expect(transaction).toContain('flock -n 8')
    expect(transaction).toContain('flock 8')
    expect(transaction).toContain('set -o noclobber')
    expect(installer).toContain('set -o noclobber')
  })

  it('tests and builds the exact event commit, never a movable checkout or latest image', () => {
    const checkout = workflow.indexOf('ref: ${{ github.sha }}')
    const tests = workflow.indexOf('run: npm test')
    const build = workflow.indexOf('make build_app VERSION="${GITHUB_SHA}"')
    const candidatePush = workflow.indexOf('make push_app VERSION="${GITHUB_SHA}"')
    expect(checkout).toBeGreaterThanOrEqual(0)
    expect(tests).toBeGreaterThan(checkout)
    expect(build).toBeGreaterThan(tests)
    expect(candidatePush).toBeGreaterThan(build)
    expect(workflow).not.toMatch(/make build_app VERSION=(?:"?)latest/)
    expect(workflow).not.toMatch(/make push_app VERSION=(?:"?)latest/)
  })

  it('rejects stale jobs before build, before publication, after publication and after transfer', () => {
    const beforeBuild = workflow.indexOf('Refuse a queued stale release before build')
    const build = workflow.indexOf('make build_app')
    const beforePublish = workflow.indexOf('Refuse a stale release before candidate publication')
    const publish = workflow.indexOf('make push_app')
    const afterPublish = workflow.indexOf('Refuse a stale release after candidate publication')
    const ssh = workflow.indexOf('uses: appleboy/ssh-action@v1.2.5')
    const decode = workflow.indexOf('decode_artifact deploy-content-transaction.sh')
    const remoteTip = workflow.indexOf('release_output="$(git ls-remote', decode)
    const invoke = workflow.indexOf('/bin/bash "$artifact_dir/deploy-content-transaction.sh"', remoteTip)
    expect([beforeBuild, build, beforePublish, publish, afterPublish, ssh, decode, remoteTip, invoke]
      .every((index) => index >= 0)).toBe(true)
    expect(beforeBuild).toBeLessThan(build)
    expect(build).toBeLessThan(beforePublish)
    expect(beforePublish).toBeLessThan(publish)
    expect(publish).toBeLessThan(afterPublish)
    expect(afterPublish).toBeLessThan(ssh)
    expect(decode).toBeLessThan(remoteTip)
    expect(remoteTip).toBeLessThan(invoke)
    expect(workflow.match(/git fetch --no-tags origin \+refs\/heads\/release:refs\/remotes\/origin\/release/g)).toHaveLength(3)
    expect(workflow.match(/tip="\$\(git rev-parse refs\/remotes\/origin\/release\)"/g)).toHaveLength(3)
  })

  it('publishes one SHA tag and deploys the registry-resolved immutable digest', () => {
    expect(workflow).toContain('candidate_ref="${IMAGE_REPOSITORY}:${GITHUB_SHA}"')
    expect(workflow).toContain("{{range .RepoDigests}}{{println .}}{{end}}")
    expect(workflow).toContain("[[ ${#repo_digests[@]} -ne 1 || ! ${repo_digests[0]} =~ ^sha256:[a-f0-9]{64}$ ]]")
    expect(workflow).toContain('EXPECTED_MANIFEST_DIGEST: ${{ steps.candidate.outputs.manifest_digest }}')
    expect(transaction).toContain('CANDIDATE_IMAGE="${IMAGE_REPOSITORY}@${EXPECTED_MANIFEST_DIGEST}"')
    expect(transaction).toContain('valid_manifest_digest "$2"')
    expect(transaction).toContain('docker --config "$AUTH_DIRECTORY" pull "$CANDIDATE_IMAGE"')
  })

  it('uses one pinned SSH action and a server-created private staging directory', () => {
    expect(workflow).not.toContain('appleboy/scp-action@')
    expect(workflow.match(/appleboy\/ssh-action@v1\.2\.5/g)).toHaveLength(1)
    expect(workflow).not.toMatch(/appleboy\/(?:scp|ssh)-action@master/)
    expect(workflow).not.toContain('/tmp/darebay-content-')
    expect(workflow).not.toContain('Remove staged deployment artifacts')
    expect(workflow).toContain('readonly staging_parent=/var/lib/darebay-content-deploy')
    expect(workflow).toContain('artifact_dir="$(mktemp -d "${staging_parent}/transaction.XXXXXX")"')
    expect(workflow).toContain("[[ $(stat -c '%u:%g:%a' -- \"$staging_parent\") == '0:0:700' ]]")
    expect(workflow).toContain("[[ $(stat -c '%u:%g:%a' -- \"$artifact_dir\") == '0:0:700' ]]")
    expect(workflow).toContain('rm -rf --one-file-system -- "$artifact_dir"')
  })

  it('authenticates every staged byte before executing root-owned artifacts', () => {
    expect(workflow).toContain('encoded="$(base64 --wrap=0 -- "$file")"')
    expect(workflow).toContain("printf '%s' \"$payload\" | base64 --decode > \"$temporary\"")
    expect(workflow).toContain('[[ "$actual_digest" == "$expected_digest" ]]')
    expect(workflow).toContain('[[ -f "$target" && ! -L "$target" && "$metadata" == "0:0:${mode}" ]]')
    expect(workflow).toContain('decode_artifact deploy-content-transaction.sh "$CONTENT_TRANSACTION_B64" "$CONTENT_TRANSACTION_SHA" 700')
    expect(transaction).toContain('artifact_contract "$script_real" 700 "$7"')
    expect(transaction).toContain("readonly STAGING_PARENT='/var/lib/darebay-content-deploy'")
    expect(transaction).toContain("[[ $STAGING_DIRECTORY =~ ^/var/lib/darebay-content-deploy/transaction\\.[A-Za-z0-9]+$ && ! -L $STAGING_DIRECTORY ]]")
    expect(transaction).toContain("[[ $parent_metadata == '0:0:700' ]]")
    expect(transaction).toContain("[[ $staging_metadata == '0:0:700' ]]")
  })

  it('proves host-side registry write access before the first production mutation', () => {
    const execute = functionBody(transaction, 'execute_transaction', 'self_test_case')
    const auth = execute.indexOf('\n  prepare_registry_auth\n')
    const candidate = execute.indexOf('\n  fetch_and_prove_candidate\n')
    const journal = execute.indexOf('\n  persist_recovery_journal\n')
    const firstMutationGuard = execute.indexOf('\n  assert_release_tip\n  set_recovery_phase container_pending\n  MUTATION_STARTED=1')
    const staleCleanup = execute.indexOf('\n  cleanup_stale_docs_containers\n', firstMutationGuard)
    const secondMutationGuard = execute.indexOf('\n  assert_release_tip\n  activate_candidate_container\n', staleCleanup)
    expect(auth).toBeGreaterThanOrEqual(0)
    expect(candidate).toBeGreaterThan(auth)
    expect(journal).toBeGreaterThan(candidate)
    expect(firstMutationGuard).toBeGreaterThan(candidate)
    expect(firstMutationGuard).toBeGreaterThan(journal)
    expect(staleCleanup).toBeGreaterThan(firstMutationGuard)
    expect(secondMutationGuard).toBeGreaterThan(staleCleanup)
    expect(transaction).toContain('ephemeral Docker registry credentials are required')
    expect(transaction).toContain('docker --config "$AUTH_DIRECTORY" push "$CANDIDATE_TAG"')
    expect(transaction).toContain('[[ $confirmed_id == "$CANDIDATE_IMAGE_ID" ]]')
  })

  it('commits registry latest only after marker, release-tip and host-route checks', () => {
    const execute = functionBody(transaction, 'execute_transaction', 'self_test_case')
    const up = execute.indexOf('\n  activate_candidate_container\n')
    const marker = execute.indexOf('\n  wait_for_expected_release\n')
    const tipAfterMarker = execute.indexOf('\n  assert_release_tip\n', marker)
    const routes = execute.indexOf('\n  install_host_routes\n')
    const hostSniMarker = execute.indexOf('\n  wait_for_host_release\n', routes)
    const tipAfterRoutes = execute.indexOf('\n  assert_release_tip\n', hostSniMarker)
    const registryPending = execute.indexOf('\n  set_recovery_phase registry_pending\n', tipAfterRoutes)
    const commit = execute.indexOf('\n  commit_registry_latest\n')
    expect(up).toBeGreaterThanOrEqual(0)
    expect(marker).toBeGreaterThan(up)
    expect(tipAfterMarker).toBeGreaterThan(marker)
    expect(routes).toBeGreaterThan(tipAfterMarker)
    expect(hostSniMarker).toBeGreaterThan(routes)
    expect(tipAfterRoutes).toBeGreaterThan(hostSniMarker)
    expect(registryPending).toBeGreaterThan(tipAfterRoutes)
    expect(commit).toBeGreaterThan(tipAfterRoutes)
    expect(transaction).toContain('if [[ $body == "$expected" ]]')
    expect(transaction).toContain("--resolve 'darebay.com:443:127.0.0.1'")
    expect(transaction).toContain("readonly HOST_RELEASE_ENDPOINT='https://darebay.com/.well-known/darebay-content-release.txt'")
  })

  it('verifies both registry commit and registry rollback before releasing the lock', () => {
    const commit = functionBody(transaction, 'commit_registry_latest', 'restore_registry_latest')
    const restore = functionBody(transaction, 'restore_registry_latest', 'rollback_container')
    expect(commit.indexOf('push "$IMAGE_LATEST"')).toBeLessThan(commit.indexOf('pull "$IMAGE_LATEST"'))
    const readback = commit.indexOf('latest_id == "$CANDIDATE_IMAGE_ID"')
    const postPushTip = commit.indexOf('assert_release_tip || return 1', readback)
    const committedJournal = commit.indexOf('set_recovery_phase committed || return 1', postPushTip)
    const committed = commit.indexOf('COMMITTED=1', committedJournal)
    expect(readback).toBeLessThan(postPushTip)
    expect(postPushTip).toBeLessThan(committedJournal)
    expect(committedJournal).toBeLessThan(committed)
    expect(restore.indexOf('push "$IMAGE_LATEST"')).toBeLessThan(restore.indexOf('pull "$IMAGE_LATEST"'))
    expect(restore).toContain('latest_id == "$OLD_IMAGE_ID"')
    expect(transaction).toContain('REGISTRY_COMMIT_STARTED == 1')
    expect(transaction).toContain('restore_registry_latest || rollback_failed=1')
  })

  it('restores the pinned container without a pull and preserves evidence on rollback failure', () => {
    const rollback = functionBody(transaction, 'rollback_container', 'load_recovery_journal')
    expect(transaction).toContain('current docs container is not running; refusing an unsafe rollback baseline')
    expect(transaction).toContain('docker image tag "$ROLLBACK_TAG" "$IMAGE_LATEST"')
    expect(rollback.indexOf('cleanup_stale_docs_containers')).toBeLessThan(rollback.indexOf('docker compose'))
    expect(transaction.match(/--pull never "\$COMPOSE_SERVICE"/g)).toHaveLength(2)
    expect(transaction).not.toContain('docker image prune')
    expect(rollback).toContain('"$ROLLBACK_READINESS_ENDPOINT"')
    expect(rollback).toContain('digest == "$OLD_READINESS_DIGEST"')
    expect(rollback).toContain('rollback container is HTTP-ready')
    expect(transaction).toContain("--output \"$response\" --write-out '%{http_code}'")
    expect(transaction).toContain('if [[ $status == 200 ]]')
    expect(transaction).toContain("self_test_case 'push-latest,rollback-registry'")
    expect(transaction).toContain('self_test_case tip4')
    expect(transaction).toContain("self_test_case 'tip5,rollback-routes'")
    expect(transaction).toContain("self_test_case 'verify,rollback-container'")
    expect(transaction).toContain('rollback FAILED; preserved image pin')
  })

  it('keeps the snippet rollback armed until nginx reload is committed', () => {
    const snapshot = functionBody(transaction, 'snapshot_previous_routes', 'cleanup_stale_docs_containers')
    const move = installer.indexOf('mv -fT -- "$candidate" "$target"')
    const reload = installer.indexOf('systemctl reload nginx', move)
    const commit = installer.indexOf('committed=1', reload)
    expect(snapshot.indexOf('install -m 0600 "$HOST_SNIPPET" "$PREVIOUS_SNIPPET"'))
      .toBeLessThan(snapshot.indexOf('managed_snippet_contract "$PREVIOUS_SNIPPET"'))
    expect(snapshot.indexOf('managed_snippet_contract "$PREVIOUS_SNIPPET"'))
      .toBeLessThan(snapshot.indexOf('PREVIOUS_SNIPPET_READY=1'))
    expect(transaction).toContain('safe_managed_snippet_syntax "$file" || return 1')
    expect(installer).toContain('safe_managed_snippet_syntax "$source_file"')
    expect(transaction).toContain("END { exit(bad || opens == 0 || opens != closes || proxies != opens) }")
    expect(transaction).toContain('/bin/bash "$INSTALLER_FILE" --restore-managed "$PREVIOUS_SNIPPET"')
    expect(installer).toContain('if [[ $# -eq 2 && $1 == --restore-managed ]]')
    expect(installer).toContain('chmod 0755 "$target_directory"')
    expect(installer).toContain('chmod 0644 "$target"')
    expect(move).toBeGreaterThanOrEqual(0)
    expect(reload).toBeGreaterThan(move)
    expect(commit).toBeGreaterThan(reload)
    expect(installer).toContain('status != 0 && target_mutated == 1 && committed == 0')
  })

  it('persists a root-private write-ahead recovery journal across process death', () => {
    const execute = functionBody(transaction, 'execute_transaction', 'self_test_case')
    const persist = execute.indexOf('\n  persist_recovery_journal\n')
    const containerPhase = execute.indexOf('\n  set_recovery_phase container_pending\n')
    const routesPhase = execute.indexOf('\n  set_recovery_phase routes_pending\n')
    const registryPhase = execute.indexOf('\n  set_recovery_phase registry_pending\n')
    expect(transaction).toContain('readonly RECOVERY_ROOT="${DEPLOY_STATE_ROOT}/content-recovery"')
    expect(transaction).toContain('ensure_private_directory "$RECOVERY_ROOT"')
    expect(transaction).toContain('install -d -o root -g root -m 0700 -- "$RECOVERY_PREPARING"')
    expect(transaction).toContain('mv -T -- "$RECOVERY_PREPARING" "$RECOVERY_ACTIVE"')
    expect(transaction).toContain('sync -f "$RECOVERY_ROOT"')
    expect(transaction).toContain('recover_incomplete_transaction')
    expect(transaction).toContain('self_test_recovery_case registry_pending')
    expect(persist).toBeGreaterThanOrEqual(0)
    expect(persist).toBeLessThan(containerPhase)
    expect(containerPhase).toBeLessThan(routesPhase)
    expect(routesPhase).toBeLessThan(registryPhase)
  })
})
