export type PublisherLocale = 'en' | 'ru' | 'uk'
export const publisherLocale = (language: string): PublisherLocale =>
  language === 'ru' || language === 'uk' ? language : 'en'

// Public availability stays explicit until the founder authorizes the product launch.
export const PUBLISHER_CONTACT = 'support@darebay.com'
export const BROLIVO_CONTACT = 'brolivo@darebay.com'
export const PUBLISHER_COPY = {
  en: {
    skip: 'Skip to content', languageLabel: 'Language',
    navProduct: 'Our app', navContact: 'Contact', back: 'All products',
    eyebrow: 'Independent apps by DareBay', title: ['Small apps.', 'Useful every day.'],
    lede: 'Thoughtful tools for the moments that matter. We are starting with Brolivo: a little help finding your next words.',
    primary: 'Meet Brolivo', secondary: 'Get in touch', status: 'Preparing for launch',
    statusNote: 'App Store and Google Play links will be added when Brolivo launches.',
    catalogLabel: 'Our first app', catalogTitle: 'Better words. Less overthinking.',
    productCategory: 'Dating & conversations',
    productSummary: 'Brolivo helps you understand a conversation, explore a reply and check a draft before you send it.',
    productLink: 'Learn about Brolivo', tags: ['Understand the context', 'Find a reply', 'Check your draft'],
    appEyebrow: 'Brolivo · Dating & conversations', appTitle: ['Brolivo.', 'Find your next words.'],
    appLede: 'A conversation helper for adults. Add context, get one suggested reply and ask for another when you need it. Choose words that sound like you.',
    appPrimary: 'How Brolivo helps', appSecondary: 'Contact us',
    processLabel: 'A little context. A clearer reply.', processSteps: ['Add the context', 'Get a reply', 'Say it your way'],
    contactLabel: 'Talk to the team', contactTitle: 'A question, an idea, a hello.',
    contactText: 'For product questions, feedback or partnerships, reach the DareBay team here.',
    appContactText: 'Have a question about Brolivo or an idea to share? Write to the team.',
    footer: 'Apps by DareBay', platform: 'Visit DareBay', copyright: 'DareBay Products',
  },
  ru: {
    skip: 'Перейти к содержимому', languageLabel: 'Язык',
    navProduct: 'Наше приложение', navContact: 'Контакты', back: 'Все продукты',
    eyebrow: 'Приложения от DareBay', title: ['Полезные приложения', 'на каждый день.'],
    lede: 'Небольшие инструменты для важных повседневных моментов. Начинаем с Brolivo — помощника, с которым проще найти слова.',
    primary: 'Знакомьтесь: Brolivo', secondary: 'Связаться с нами', status: 'Готовимся к запуску',
    statusNote: 'Ссылки на App Store и Google Play появятся после запуска Brolivo.',
    catalogLabel: 'Наше первое приложение', catalogTitle: 'Проще ответить. Меньше сомнений.',
    productCategory: 'Знакомства и общение',
    productSummary: 'Brolivo помогает разобраться в переписке, подобрать ответ и проверить черновик перед отправкой.',
    productLink: 'Подробнее о Brolivo', tags: ['Понять контекст', 'Подобрать ответ', 'Проверить черновик'],
    appEyebrow: 'Brolivo · Знакомства и общение', appTitle: ['Brolivo.', 'Проще найти слова.'],
    appLede: 'Помощник в общении для взрослых. Добавьте контекст, получите один ответ и при желании запросите другой вариант. Выберите слова, которые звучат по-вашему.',
    appPrimary: 'Чем поможет Brolivo', appSecondary: 'Написать нам',
    processLabel: 'Чуть больше контекста. Яснее ответ.', processSteps: ['Добавить контекст', 'Получить ответ', 'Сказать по-своему'],
    contactLabel: 'Связаться с командой', contactTitle: 'Вопрос, идея или просто привет.',
    contactText: 'По вопросам о продуктах, с обратной связью или предложением о сотрудничестве напишите команде DareBay.',
    appContactText: 'Есть вопрос о Brolivo или идея, которой хочется поделиться? Напишите команде.',
    footer: 'Приложения от DareBay', platform: 'Перейти на DareBay', copyright: 'DareBay Products',
  },
  uk: {
    skip: 'Перейти до вмісту', languageLabel: 'Мова',
    navProduct: 'Наш застосунок', navContact: 'Контакти', back: 'Усі продукти',
    eyebrow: 'Застосунки від DareBay', title: ['Корисні застосунки', 'на щодень.'],
    lede: 'Невеликі інструменти для важливих щоденних моментів. Починаємо з Brolivo — помічника, з яким легше знайти слова.',
    primary: 'Знайомтеся: Brolivo', secondary: 'Зв’язатися з нами', status: 'Готуємося до запуску',
    statusNote: 'Посилання на App Store і Google Play з’являться після запуску Brolivo.',
    catalogLabel: 'Наш перший застосунок', catalogTitle: 'Легше відповісти. Менше сумнівів.',
    productCategory: 'Знайомства та спілкування',
    productSummary: 'Brolivo допомагає розібратися в листуванні, підібрати відповідь і перевірити чернетку перед надсиланням.',
    productLink: 'Докладніше про Brolivo', tags: ['Зрозуміти контекст', 'Підібрати відповідь', 'Перевірити чернетку'],
    appEyebrow: 'Brolivo · Знайомства та спілкування', appTitle: ['Brolivo.', 'Легше знайти слова.'],
    appLede: 'Помічник у спілкуванні для дорослих. Додайте контекст, отримайте одну відповідь і за бажанням запитайте інший варіант. Оберіть слова, які звучать по-вашому.',
    appPrimary: 'Як допоможе Brolivo', appSecondary: 'Написати нам',
    processLabel: 'Трохи більше контексту. Ясніша відповідь.', processSteps: ['Додати контекст', 'Отримати відповідь', 'Сказати по-своєму'],
    contactLabel: 'Зв’язатися з командою', contactTitle: 'Питання, ідея чи просто привіт.',
    contactText: 'Із запитаннями про продукти, відгуками чи пропозиціями співпраці напишіть команді DareBay.',
    appContactText: 'Маєте запитання про Brolivo чи ідею, якою хочете поділитися? Напишіть команді.',
    footer: 'Застосунки від DareBay', platform: 'Перейти на DareBay', copyright: 'DareBay Products',
  },
} as const
